---
version: '3'
services:
  file-browser:
    image: filebrowser/filebrowser:latest
    container_name: file-browser
    user: 1000:1000
    ports:
      - 8081:80
    volumes:
      - /home/buurmans/:/srv
      # manually make the database.db & .filebrowser.json
      # touch /home/buurmans/docker/filebrowser/database.db
      - /home/buurmans/docker/filebrowser/database.db:/database.db
      - /home/buurmans/docker/filebrowser/.filebrowser.json:/.filebrowser.json
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true