version: '3'
services:
  file-browser:
    image: filebrowser/filebrowser:latest
    container_name: file-browser
    user: 1000:1000
    environment:
      - TZ=Europe/Brussels
    ports:
      - 8081:80
    volumes:
      - /home/buurmans/shares:/srv
      - /home/buurmans/docker/filebrowser/database.db:/database.db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    ports:
      - 8080:8080
    network_mode: host
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'