---
version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:latest
    privileged: true
    user: root
    ports:
      - 8083:8080
      - 50003:50000
    container_name: jenkins
    volumes:
      - /buurmans/docker/jenkins/data:/var/jenkins_home
      - /buurmans/docker/jenkins/docker.sock:/var/run/docker.sock
