version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert:latest"      
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - /home/buurmans/docker/pialert/config:/home/pi/pialert/config
      - /home/buurmans/docker/pialert/db:/home/pi/pialert/db      
      # (optional) useful for debugging if you have issues setting up the container
      #- local/path/logs:/home/pi/pialert/front/log
    environment:
      - TZ=Europe/Brussels      
      - HOST_USER_ID=1000
      - HOST_USER_GID=1000
      - PORT=20211