version: '3.8'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    ports:
      - 9443:9443
      - 8000:8000
      - 9000:9000
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/buurmans/docker/portainer/data:/data

  cloudflare-tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token $CLOUDFLARE_TUNNEL_TOKEN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels

# create .env file
# Cloudflare Tuennel Token
# CLOUDFLARE_TUNNEL_TOKEN=MyLovelyToken