version: '3.8'
services:
  portainer:
    container_name: portainer_agent
    image: portainer/agent:latest
    environment:
      - PUID=1000
      - PGID=1000       
      - TZ=Europe/Brussels
    ports:
      - 9001:9001
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes