---
version: '3.8'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    environment:
      - PUID=1000
      - PGID=1000       
      - TZ=Europe/Brussels
    ports:
      - 9000:9000
      - 8000:8000
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/mos/docker/portainer/data:/data

---
version: "3.1"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    environment:
      - TZ=Europe/Brussels
    volumes:
      - /home/mos/docker_volumes/uptime-kuma/data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true