#https://github.com/jlesage/docker-handbrake
---
version: '3'
services:
  handbrake:
    image: jlesage/handbrake:latest
    ports:
      - 5800:5800
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /home/buurmans/docker/handbrake/appdata:/config:rw
      - /home/buurmans/docker/handbrake/storage:/storage:ro
      - /home/buurmans/vault-share/media/handbrake/watch:/watch:rw
      - /home/buurmans/vault-share/media/handbrake/output:/output:rw

#pct set 222 -mp0 /mnt/pve/usbdrive/share/handbrake,mp=/home/buurmans/docker/handbrake/media
#pct set 222 -mp1 /mnt/app_backup,mp=/home/buurmans/backups

# settings for handbrake on proxmoxL
# pct set 232 -mp0 /mnt/pve/vault/handbrake,mp=/home/buurmans/docker/handbrake/media

volumes:
  - /home/buurmans/docker/handbrake/appdata:/config:rw
  - /home/buurmans/docker/handbrake/storage:/storage:ro
  - /home/buurmans/docker/handbrake/media/watch:/watch:rw
  - /home/buurmans/docker/handbrake/media/output:/output:rw



