#https://github.com/jlesage/docker-handbrake
---
version: '3'
services:
  handbrake:
    container_name: handbrake
    image: jlesage/handbrake:latest
    ports:
      - 5800:5800
    restart: unless-stopped
    environment:
      - TZ=Europe/Brussels
      - DARK_MODE=1
    volumes:
      - /home/buurmans/docker/handbrake/appdata:/config:rw
      - /home/buurmans/docker/handbrake/storage:/storage:ro
      - /home/buurmans/share/handbrake/watch:/watch:rw
      - /home/buurmans/share/handbrake/output:/output:rw

# BuurmansBigNas
# pct set 223 -mp0 /mnt/pve/buurmans-big-nas-share/application_data,mp=/home/buurmans/share
# chown -R nobody:nogroup /mnt/pve/buurmans-big-nas-share/application_data/handbrake/
# chmod -R a+rwx /mnt/pve/buurmans-big-nas-share/application_data/handbrake/