#https://github.com/jlesage/docker-handbrake
---
version: '3'
services:
  handbrake:
    image: jlesage/handbrake:latest
    ports:
      - 5800:5800
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /home/buurmans/docker/handbrake/appdata:/config:rw
      - /home/buurmans/docker/handbrake/storage:/storage:ro        
      - /home/buurmans/share/handbrake/watch:/watch:rw
      - /home/buurmans/share/handbrake/output:/output:rw

#pct set 233 -mp0 /mnt/pve/truenas-share/media,mp=/home/buurmans/share



