---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - VERSION=docker
      - PLEX_CLAIM=myMofoLovelyClaim
    volumes:
      - /home/buurmans/docker/plex/config:/config
      - /home/buurmans/share/tvshows:/tv
      - /home/buurmans/share/movies:/movies
      - /home/buurmans/share/music:/music
      - /home/buurmans/docker/plex/transcode:/transcode
    restart: unless-stopped
    
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels      
    volumes:
      - /home/buurmans/docker/duplicati/config:/config
      - /home/buurmans/backups/duplicati/PlexServer:/app_backups_on_nas
      - /home/buurmans:/buurmans_home_dir
    ports:
      - 8200:8200
    restart: unless-stopped