global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.2.204:9100']
  
  - job_name: 'pve'
    static_configs:
      - targets:
        - 192.168.2.230:9221
    metrics_path: /pve
    params:
      module: [default]    

#ssh root@192.168.2.206
#nano /etc/prometheus/prometheus.yml
#systemctl restart prometheus