---
version: '3.5'

services:
  photoprism:
    image: photoprism/photoprism:latest
    ## Don't enable automatic restarts until PhotoPrism has been properly configured and tested!
    ## If the service gets stuck in a restart loop, this points to a memory, filesystem, network, or database issue:
    ## https://docs.photoprism.app/getting-started/troubleshooting/#fatal-server-errors
    restart: unless-stopped
    stop_grace_period: 10s
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342"
    env_file:
      - stack.env
    working_dir: "/photoprism" # do not change or remove
    ## Storage Folders: "~" is a shortcut for your home directory, "." for the current directory
    volumes:
      - "/home/buurmans/share/photoprism/output:/photoprism/originals" # Originals mount path can be changed as needed (DO NOT REMOVE)
      - "/home/buurmans/share/photoprism/import:/photoprism/import"
      - "/home/buurmans/docker/storage:/photoprism/storage"     # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)

  mariadb:
    image: mariadb:10.11
    ## If MariaDB gets stuck in a restart loop, this points to a memory or filesystem issue:
    ## https://docs.photoprism.app/getting-started/troubleshooting/#fatal-server-errors
    restart: unless-stopped
    stop_grace_period: 5s
    security_opt: # see https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1136151239
      - seccomp:unconfined
      - apparmor:unconfined
    command: mariadbd --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - "/home/buurmans/docker/database:/var/lib/mysql" # DO NOT REMOVE
    env_file:
      - stack.env

# pct set 234 -mp0 /mnt/pve/truenas-share/share/photoprism,mp=/home/buurmans/share/photoprism

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

#pct set 220 -mp0 /mnt/pve/buurmans-big-nas-share/application_data/photoprism,mp=/home/buurmans/share/photoprism
