---
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: Europe/Brussels      
      #WATCHTOWER_MONITOR_ONLY: 'true'
      WATCHTOWER_SCHEDULE: 0 45 03 * * *
      #WATCHTOWER_POLL_INTERVAL: 30
      WATCHTOWER_NOTIFICATIONS: shoutrrr	  
      WATCHTOWER_NOTIFICATION_URL: discord://TOKEN@CHANNEL
      WATCHTOWER_NOTIFICATION_TEMPLATE: |-
       portainer {{range .}}{{.Time.Format "02-01-2006 15:04:05"}} ({{.Level}}): {{.Message}}{{println}}{{end}}

#-e WATCHTOWER_NOTIFICATIONS=email
#-e WATCHTOWER_NOTIFICATION_EMAIL_FROM=you@gmail.com
#-e WATCHTOWER_NOTIFICATION_EMAIL_TO=you@gmail.com
#-e WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
#-e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
#-e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=you@gmail.com
#-e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=your_gmail_app_password


---
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: Europe/Brussels      
      #WATCHTOWER_MONITOR_ONLY: 'true'
      WATCHTOWER_SCHEDULE: 0 15 04 * * *
      #WATCHTOWER_POLL_INTERVAL: 30
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_NO_STARTUP_MESSAGE: true      
      WATCHTOWER_NOTIFICATIONS: shoutrrr	  
      WATCHTOWER_NOTIFICATION_URL: discord://TOKEN@CHANNEL
      WATCHTOWER_NOTIFICATION_TEMPLATE: |-
       Protainer {{range .}}{{.Time.Format "02-01-2006 15:04:05"}} ({{.Level}}): {{.Message}}{{println}}{{end}}
