---
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_SCHEDULE: "0 0 0 * * *"

#            Argument: --schedule, -s
#Environment Variable: WATCHTOWER_SCHEDULE
#                Type: String
#             Default: -

#Entry                  | Description                                | Equivalent To
#-----                  | -----------                                | -------------
#@yearly (or @annually) | Run once a year, midnight, Jan. 1st        | 0 0 0 1 1 *
#@monthly               | Run once a month, midnight, first of month | 0 0 0 1 * *
#@weekly                | Run once a week, midnight between Sat/Sun  | 0 0 0 * * 0
#@daily (or @midnight)  | Run once a day, midnight                   | 0 0 0 * * *
#@hourly                | Run once an hour, beginning of hour        | 0 0 * * * *


#-e WATCHTOWER_NOTIFICATIONS=email
#-e WATCHTOWER_NOTIFICATION_EMAIL_FROM=you@gmail.com
#-e WATCHTOWER_NOTIFICATION_EMAIL_TO=you@gmail.com
#-e WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
#-e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
#-e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=you@gmail.com
#-e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=your_gmail_app_password
