---
version: '3'
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /home/buurmans/docker/sabnzbd/config:/config
      - /home/buurmans/share/downloads/complete:/downloads
      - /home/buurmans/share/downloads/incomplete:/incomplete-downloads
    ports:
      - 8080:8080
    restart: unless-stopped

# BuurmansBigNas
# pct set 222 -mp0 /mnt/pve/buurmans-big-nas-share/application_data/sabnzb,mp=/home/buurmans/share/
# chown -R nobody:nogroup /mnt/pve/buurmans-big-nas-share/application_data/sabnzb/
# chmod -R a+rwx /mnt/pve/buurmans-big-nas-share/application_data/sabnzb/