---
version: "2.1"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - MYSQL_ROOT_PASSWORD=ROOT_ACCESS_PASSWORD
      - MYSQL_DATABASE=USER_DB_NAME
      - MYSQL_USER=MYSQL_USER
      - MYSQL_PASSWORD=DATABASE_PASSWORD
      #- REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql
    volumes:
      - /home/buurmans/docker/mariadb/config:/config
    ports:
      - 3306:3306
    restart: unless-stopped