 global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["192.168.2.207:9090"]

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.2.207:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.2.207:8080']

#ssh root@192.168.2.206
#nano /etc/prometheus/prometheus.yml
#systemctl restart prometheus