--- 
version: '2'

services:
  db: 
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes: 
      - /home/buurman/nextcloud/db:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=HJ3NHYqLHYuh9fDGkvxWV2oS2eFM3ZMi5oNVAWQsROOT
      - MYSQL_PASSWORD=HJ3NHYqLHYuh9fDGkvxWV2oS2eFM3ZMi5oNVAWQs
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  app: 
    image: nextcloud
    restart: always
    ports: 
      - 8080:80
    links: 
      - db
    depends_on: 
      - db
    volumes: 
      - /home/buurman/nextcloud/nextcloud:/var/www/html
      - /home/buurman/nextcloud/custom_apps:/var/www/html/custom_apps
      - /home/buurman/nextcloud/config:/var/www/html/config
      - /home/buurman/nextcloud/data:/var/www/html/data
      - /home/buurman/nextcloud/theme:/var/www/html/themes
    environment: 
      - MYSQL_PASSWORD=HJ3NHYqLHYuh9fDGkvxWV2oS2eFM3ZMi5oNVAWQs
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=HJ3NHYqLHYuh9fDGkvxWV2oS2eFM3ZMi5oNVAWQsROOT
    

#pct set 214 -mp0 /mnt/pve/truenas-share/share/nextcloud,mp=/home/buurmans/share/
    

Redirect 301 /.well-known/carddav https://nextcloud.buurmans.info/remote.php/dav
Redirect 301 /.well-known/caldav https://nextcloud.buurmans.info/remote.php/dav
Redirect 301 /.well-known/webdav https://nextcloud.buurmans.info/remote.php/dav
Redirect 301 /.well-known/webfinger https://nextcloud.buurmans.info/index.php
Redirect 301 /.well-known/nodeinfo https://nextcloud.buurmans.info/index.php


php_value upload_max_filesize 16G
php_value post_max_size 16G
php_value max_input_time 3600
php_value max_execution_time 3600
php_value memory_limit 2048M