---
#sudo docker compose up -d --force-recreate --remove-orphans
version: '3'
services:

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "/home/buurmans/docker/navidrome/data:/data"
      - "/home/buurmans/share/music:/music:ro"
    ports:
      - "4533:4533"
    restart: unless-stopped
  
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels      
    volumes:
      - /home/buurmans/docker/duplicati/config:/config
      - /home/buurmans/backups/duplicati/MediaServer:/app_backup_on_nas
      - /home/buurmans:/buurmans_home_dir
    ports:
      - 8200:8200
    restart: unless-stopped

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    ports:
      - 9000:9000
      - 8000:8000
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/buurmans/docker/portainer/data:/data

  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TZ=Europe/Brussels
    volumes:
      - /home/buurmans/docker/beets/config:/config
      - /home/buurmans/share/music:/music
      - /home/buurmans/share/downloads/complete:/downloads
    ports:
      - 8337:8337
    restart: no